lang: en

root_dir: ..
exp_dir: !ref <root_dir>/exp/miami_<lang>
models_dir:  !ref <root_dir>/models
results_summary_dir: !ref <exp_dir>/results_summary/eval_pre_miami_<lang>

datasets:
  - name: miami-en_test
    data: miami-en
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]


eval_steps:  # all metrics in this list will be computed in the evaluation. Remove entry to skip
  privacy:
    - asv
  utility:
    - asr

anon_data_suffix: anon  # suffix for dataset to signal that it is anonymized
eval_data_dir: !ref <root_dir>/results/miami/<lang>/formatted_data/ims_sttts
  # path to anonymized evaluation data in kaldi format, e.g. <eval_data_dir>/libri_test_enrolls/wav.scp etc.

privacy:
  asv:
    model_dir: !ref <models_dir>/exp/asv_orig  # path to existing ASV model or output for trained ASV model
    vec_type: ecapa  # ecapa or xvector
    evaluation:
      results_dir: !ref <exp_dir>/asv_orig_<privacy[asv][vec_type]>  # path to save evaluation results
      distance: cosine  # cosine or plda
      plda:   # ignored if distance is not plda
        model_dir: null  # path to trained PLDA or output of PLDA training
        train_data_dir: null # path to PLDA training data
        anon: null # trained on anonymized (true) or original (false) data

utility:
  asr:
    backend: whisper
    model_name: asr_orig_whisper  # name for ASR model
    model_dir: !ref <models_dir>/whisper-large-v3
    libri_dir: null

    evaluation:
      model_dir: !ref <utility[asr][model_dir]>
      model_path: !ref <utility[asr][model_dir]>
      model_url: !ref <utility[asr][model_dir]>
      batch_size: 16
      results_dir: !ref <exp_dir>/<utility[asr][model_name]>
      recognizer: !ref <utility[asr][backend]>
      lang: !ref <lang>
      dataset_languages:
        - en
        - es